# This config file is used by ros2_control

controller_manager:
  ros__parameters:
    update_rate: 100

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    velocity_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    effort_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


arm_controller:
  ros__parameters:

    joints:
      - yaw_joint
      - pitch_joint
      - trans_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: false #是否允许部分关节动，默认不允许


velocity_controller:
  ros__parameters:

    joints:
      - yaw_joint
      - pitch_joint
      - trans_joint

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: false


effort_controller:
  ros__parameters:

    joints:
      - yaw_joint
      - pitch_joint
      - trans_joint

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: false